# Generated by Django 5.1.1 on 2024-09-30 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
            },
        ),
        migrations.CreateModel(
            name='RoomTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite')], max_length=15, verbose_name='Room Size')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('available_rooms', models.IntegerField(verbose_name='Available Rooms')),
                ('price', models.IntegerField()),
                ('Amenities', models.ManyToManyField(to='hotel.amenity')),
            ],
        ),
        migrations.CreateModel(
            name='RoomRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='Rating')),
                ('roomtier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.roomtier', verbose_name='Room Tier')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
                ('roomtier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.roomtier')),
            ],
        ),
    ]
