# Generated by Django 5.1.1 on 2024-10-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtier',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='roomtier',
            name='room_type',
            field=models.CharField(max_length=40, verbose_name='Room Type'),
        ),
    ]
